travis:
  secure:
    BINSTAR_TOKEN: eVgNm2+ychDfKXP9sTF44hV+GO9/82xuSfPcMU/I0xQQgqO+NI7WuDqYtNJCNCcfgse9V1o5qmSDPcb9Oe52snbv/M3w2wCULnI1JBSdOqrCCdJ/1cqEP3P/LM+Ej8LMKzyE4Gv1PPv+kSUJKiSTz533LMKhWJbjYN+f+TQppxC+Cm1zaOhm8Oi8MDQHQK3QJjWZRKzO2K9Xk3qbckM+VmbGwaXubU1yh3U43wDGTCU0eYcfWGt/kMj1uiu5VFHdUo+61+5V1395e8w9jhyom0m7pTcm1a4uPl4kM1ZdpMgkSXDQE3jdInV8kQr/FKlu1fRI6bKcpus+6ZUyh2/4oTTqIWvffvCY+aMsEkriwOgQz75MRXGoVTigO2b2LgNJm5z7FeSiQ2GXn1rn9QAG8vwPx5ILeHToE3LFEdFARQ8ze228KkLDs53OHE4MQPFZozrcD5ngAPYsEbzQuWWlGFtTjxCeiTtUnuRDbfIHWYLLk6Z185HaP7guGmTMKgv+09/dCIWekINrsnnE3FyjzPZByr40rWnEwIcuM4EwsOnCKksoCMtaWg8+ViuWInQUvDo1gWWPrXtWZJLLjcZe3vborQeG878mPkGk/h3mzWi5fI21UN1PAQIW41ugru4MuovWxCOMCx3qh5bEO552rZAjD2utRpDmorTVT7lpVL8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
